// @ts-nocheck
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	setSettings: (settings: Settings) => __TAURI_INVOKE<null>("set_settings", { settings }),
	/**  Subfolders of the projects folder, with PDF thumbnails (rendered on first use). */
	listProjects: () => __TAURI_INVOKE<ProjectItem[]>("list_projects"),
	/**
	 *  Opens `path` as the project: indexes it, starts the file watcher and lets the
	 *  webview load its files (PDFs, images) through the asset protocol.
	 */
	openProject: (path: string) => __TAURI_INVOKE<ProjectInfo>("open_project", { path }),
	closeProject: () => __TAURI_INVOKE<null>("close_project"),
	fileTree: () => __TAURI_INVOKE<TreeNode[]>("file_tree"),
	readFile: (path: string) => __TAURI_INVOKE<string>("read_file", { path }),
	/**  Saves `content` to `path`. Project `.tex`/`.bib` files are reindexed right away. */
	writeFile: (path: string, content: string) => __TAURI_INVOKE<null>("write_file", { path, content }),
	/**  Creates an empty file inside the project; fails if it already exists. */
	createFile: (path: string) => __TAURI_INVOKE<null>("create_file", { path }),
	createFolder: (path: string) => __TAURI_INVOKE<null>("create_folder", { path }),
	/**  Renames or moves within the project; fails if the destination exists. */
	renamePath: (from: string, to: string) => __TAURI_INVOKE<null>("rename_path", { from, to }),
	/**  Moves a file or folder inside the project to the Trash. */
	deletePath: (path: string) => __TAURI_INVOKE<null>("delete_path", { path }),
	/**  Opens an existing file in its default app (e.g. a PDF in Preview). URLs are refused. */
	openExternal: (path: string) => __TAURI_INVOKE<null>("open_external", { path }),
	/**  Lets the webview load one more file (a PDF or image opened from outside the project). */
	grantFileAccess: (path: string) => __TAURI_INVOKE<null>("grant_file_access", { path }),
	/**  Exits the app (after the UI has dealt with unsaved changes). */
	quit: () => __TAURI_INVOKE<void>("quit"),
	indexStats: () => __TAURI_INVOKE<IndexStats>("index_stats"),
	/**  Sections of every indexed file, in file then line order. */
	outline: () => __TAURI_INVOKE<SectionItem[]>("outline"),
	labels: () => __TAURI_INVOKE<LabelEntry[]>("labels"),
	/**  TODO/FIXME comments; `file` limits them to one file. */
	todos: (file: string | null) => __TAURI_INVOKE<TodoItem[]>("todos", { file }),
	tables: (file: string | null) => __TAURI_INVOKE<TableItem[]>("tables", { file }),
	/**
	 *  Suggestions at UTF-16 column `cursor` of `line`; `null` when there is nothing to complete.
	 *  Ranking uses `file` to prefer labels defined nearby.
	 */
	complete: (line: string, cursor: number, file: string | null) => __TAURI_INVOKE<{
	/**  Replacement range on the line, in UTF-16 units. */
	from: number,
	to: number,
	/**  The text being completed (what the matcher ranked against). */
	query: string,
	items: CompletionItem[],
} | null>("complete", { line, cursor, file }),
	/**  The document a build of `active` compiles: honors `%!TEX root`, else the project's main file. */
	mainDocument: (active: string | null) => __TAURI_INVOKE<{
	path: string,
	engine: Engine,
	/**  Where the PDF goes (it may not exist yet). */
	pdfPath: string,
} | null>("main_document", { active }),
	/**
	 *  Compiles the main document for `active`. The UI saves dirty buffers first.
	 *  Emits `build-started` and `build-finished`.
	 */
	build: (active: string | null) => __TAURI_INVOKE<BuildResult>("build", { active }),
	/**  Removes auxiliary files, then builds from scratch. */
	cleanBuild: (active: string | null) => __TAURI_INVOKE<BuildResult>("clean_build", { active }),
	/**
	 *  Where `line` (1-based) of `file` appears in the PDF. `pdf` defaults to the main
	 *  document's PDF. `null` when there is no SyncTeX data (build first).
	 */
	synctexForward: (file: string, line: number, pdf: string | null) => __TAURI_INVOKE<{
	/**  1-based page number */
	page: number,
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
} | null>("synctex_forward", { file, line, pdf }),
	/**  The source location under (`x`, `y`) on 1-based `page` of `pdf`. */
	synctexInverse: (pdf: string, page: number, x: number | null, y: number | null) => __TAURI_INVOKE<{
	/**  Absolute, normalized path of the source file. */
	file: string,
	/**  1-based. */
	line: number,
	/**  0-based; 0 when SyncTeX doesn't know the column. */
	column: number,
} | null>("synctex_inverse", { pdf, page, x, y }),
	/**  `null` when the project is not in a git repository. */
	gitStatus: () => __TAURI_INVOKE<{
	root: string,
	branch: string | null,
	/**  Paths are relative to `root`. */
	changes: FileStatus[],
} | null>("git_status"),
	/**  Commits touching `file`, or the whole project when `file` is `null`; newest first. */
	gitHistory: (file: string | null, limit: number) => __TAURI_INVOKE<Commit[]>("git_history", { file, limit }),
	/**  Diff of `path` at `rev` (default `HEAD`) against `buffer` (unsaved editor text), or the file on disk. */
	gitDiff: (path: string, rev: string | null, buffer: string | null) => __TAURI_INVOKE<FileDiff>("git_diff", { path, rev, buffer }),
	/**
	 *  Added/modified/removed markers for the editor gutter: `buffer` against the committed `path`.
	 *  Untracked files and files outside a repository get no markers.
	 */
	gitLineMarkers: (path: string, buffer: string) => __TAURI_INVOKE<GutterMarkers>("git_line_markers", { path, buffer }),
	/**  What the "Compare versions" dialog offers. Fails when the project isn't under git. */
	latexdiffOptions: (active: string | null) => __TAURI_INVOKE<LatexDiffOptions>("latexdiff_options", { active }),
	/**
	 *  Builds a change-tracking PDF of `old_rev` → `new_rev` (`null` = working copy, saved to disk)
	 *  next to the main document, and returns its path.
	 */
	latexdiff: (active: string | null, oldRev: string, newRev: string | null) => __TAURI_INVOKE<string>("latexdiff", { active, oldRev, newRev }),
	/**
	 *  Grammar and spelling issues in `text` (a whole `.tex` buffer). `dialect` defaults to the setting.
	 *  Citations are read as author–year text using the project's bibliography.
	 */
	grammarCheck: (text: string, dialect: "american" | "british" | "canadian" | "australian" | "indian" | null) => __TAURI_INVOKE<GrammarIssue[]>("grammar_check", { text, dialect }),
	/**  The math span (`$…$`, `\[…\]`, `equation`, `align`, …) containing the position, if any. */
	mathAt: (text: string, line: number, col: number) => __TAURI_INVOKE<{
	/**  0-based lines and UTF-16 columns; `to` is exclusive. */
	fromLine: number,
	fromCol: number,
	toLine: number,
	toCol: number,
	/**  "inline math", "display math" or the environment name. */
	label: string,
	/**  Standalone LaTeX for `math_render`. */
	snippet: string,
} | null>("math_at", { text, line, col }),
	/**
	 *  Typesets `snippet` (from `math_at`) with the macros and math packages of `text`,
	 *  in `color` (`RRGGBB`). Returns a PNG under `~/.vortex-editor/math_cache`; results are cached.
	 */
	mathRender: (text: string, file: string | null, snippet: string, color: string) => __TAURI_INVOKE<RenderedMath>("math_render", { text, file, snippet, color }),
	/**  The table in `source` (a `table` or `tabular` environment), or a starter table. */
	tableLoad: (source: string) => __TAURI_INVOKE<TableModel>("table_load", { source }),
	tableApply: (model: TableModel, op: TableOp) => __TAURI_INVOKE<TableModel>("table_apply", { model, op }),
	tableLatex: (model: TableModel) => __TAURI_INVOKE<string>("table_latex", { model }),
};

/** Events */
export const events = {
	buildFinished: makeEvent<BuildFinished>("build-finished"),
	buildStarted: makeEvent<BuildStarted>("build-started"),
	fsChanged: makeEvent<FsChanged>("fs-changed"),
	gitChanged: makeEvent<GitChanged>("git-changed"),
	indexUpdated: makeEvent<IndexUpdated>("index-updated"),
	menuCommand: makeEvent<MenuCommand>("menu-command"),
};

/* Types */
export type BuildFinished = BuildResult;

export type BuildResult = {
	success: boolean,
	/**  Short summary for the status bar. */
	message: string,
	/**  The main document that was compiled. */
	mainFile: string,
	engine: Engine,
	/**  Set when this build wrote the PDF (also on failed builds that still produced one). */
	pdfPath: string | null,
	diagnostics: Diagnostic[],
	/**  The TeX `.log`, or latexmk's own output when TeX never ran. */
	rawLog: string,
	durationMs: number,
};

export type BuildStarted = {
	mainFile: string,
};

export type ChangeKind = "modified" | "added" | "deleted" | "renamed" | "untracked" | "conflicted";

export type ColAlign = "Left" | "Center" | "Right" | { Paragraph: string };

export type ColumnSpec = {
	alignment: ColAlign,
	borderLeft: boolean,
	borderRight: boolean,
};

export type Commit = {
	hash: string,
	shortHash: string,
	author: string,
	relativeDate: string,
	subject: string,
};

export type CompletionItem = {
	label: string,
	kind: CompletionKind,
	detail: string | null,
	documentation: string | null,
	/**  Replaces `from..to` on the line; may span several lines (already indented). */
	insertText: string,
	/**  Where the cursor goes, in UTF-16 units from the start of `insert_text`. */
	cursorOffset: number,
};

export type CompletionKind = "reference" | "citation" | "environment" | "command";

export type Completions = {
	/**  Replacement range on the line, in UTF-16 units. */
	from: number,
	to: number,
	/**  The text being completed (what the matcher ranked against). */
	query: string,
	items: CompletionItem[],
};

export type Diagnostic = {
	severity: Severity,
	/**  Absolute path of the source file, when the log says which one. */
	file: string | null,
	/**  1-based line in `file`. */
	line: number | null,
	message: string,
};

export type DiffLineKind = "context" | "added" | "removed";

export type DiffRow = { type: "line"; kind: DiffLineKind; oldNo: number | null; newNo: number | null; text: string; 
/**  Byte ranges within `text` that changed (word-level), for emphasis. */
emphasis: Range<number>[] } | 
/**  Collapsed run of unchanged lines. */
{ type: "skipped"; lines: number };

export type Engine = "pdflatex" | "xelatex" | "lualatex";

export type FileChangeEvent = {
	type: string,
	kind: WatchedKind,
	path: string,
	relativePath: string | null,
};

export type FileDiff = {
	rows: DiffRow[],
	added: number,
	removed: number,
};

export type FileStatus = {
	/**  Path relative to the repository root. */
	path: string,
	kind: ChangeKind,
};

/**  A watched file changed on disk: sources, PDFs (reload the viewer) or git metadata. */
export type FsChanged = FileChangeEvent;

/**  Repository state may have changed (working tree edit, commit, checkout, stage). */
export type GitChanged = null;

export type GitStatus = {
	root: string,
	branch: string | null,
	/**  Paths are relative to `root`. */
	changes: FileStatus[],
};

/**  English spelling conventions to check against. */
export type GrammarDialect = "american" | "british" | "canadian" | "australian" | "indian";

export type GrammarIssue = {
	/**  0-based line. */
	line: number,
	/**  UTF-16 columns on that line. */
	from: number,
	to: number,
	message: string,
};

export type GutterMarkers = {
	/**  Per buffer row of the new text. */
	lines: (LineChange | null)[],
	/**  Rows *after which* lines were removed; `None` entry = removed before row 0. */
	removedAfter: (number | null)[],
};

export type IndexStats = {
	labels?: number,
	bibentries?: number,
	filesIndexed?: number,
	project: string | null,
};

/**  The semantic index changed (project opened, or a `.tex`/`.bib` file changed). */
export type IndexUpdated = IndexStats;

export type LabelEntry = {
	key: string,
	file: string,
	filename: string,
	line: number,
	kind: LabelKind,
};

/**  What a label points at, guessed from its prefix (`fig:`, `eq:`, `sec:` ...). */
export type LabelKind = "section" | "equation" | "table" | "figure" | "other";

export type LatexDiffOptions = {
	repoRoot: string,
	/**  Repo-relative project folder that each version is taken from ("" = whole repo). */
	scope: string,
	/**  Repo-relative main document, if one was found. */
	mainRel: string | null,
	/**  Commits touching the project, newest first. */
	commits: Commit[],
};

export type LineChange = "added" | "modified";

export type MainDocument = {
	path: string,
	engine: Engine,
	/**  Where the PDF goes (it may not exist yet). */
	pdfPath: string,
};

export type MathAt = {
	/**  0-based lines and UTF-16 columns; `to` is exclusive. */
	fromLine: number,
	fromCol: number,
	toLine: number,
	toCol: number,
	/**  "inline math", "display math" or the environment name. */
	label: string,
	/**  Standalone LaTeX for `math_render`. */
	snippet: string,
};

/**
 *  A menu item or its shortcut was used. `closeWindow` is sent when the user closes
 *  the window, so the UI can ask about unsaved changes and then call `quit`.
 */
export type MenuCommand = "quit" | "closeWindow" | "newTab" | "openFile" | "openFolder" | "save" | "closeTab" | "showProjects" | "changeProjectsFolder" | "undo" | "redo" | "find" | "toggleComment" | "insertTable" | "toggleSidebar" | "cycleTheme" | "build" | "cleanBuild" | "syncPdf" | "compareVersions";

export type ProjectInfo = {
	/**  Canonical path of the project folder. */
	path: string,
	name: string,
	tree: TreeNode[],
	stats: IndexStats,
};

export type ProjectItem = {
	name: string,
	path: string,
	previewPdf: string | null,
	previewImage?: string | null,
};

export type Range<T> = {
	start: T,
	end: T,
};

export type RenderedMath = {
	pngPath: string,
	/**  Size of the typeset math in PDF points. */
	widthPt: number | null,
	heightPt: number | null,
};

export type RuleKind = "Toprule" | "Midrule" | "Bottomrule" | "Hline" | { Cline: string };

export type SectionItem = {
	type: string | null,
	level: number,
	title: string,
	file: string,
	line: number,
};

export type Settings = {
	/**  Folder whose subfolders are listed as projects. */
	projectsFolder?: string | null,
	/**  The project that was open last. */
	currentProject?: string | null,
	themePreference?: ThemePreference,
	grammarDialect?: GrammarDialect,
};

export type Severity = "error" | "warning" | 
/**  Overfull/underfull boxes: typesetting quality, not correctness. */
"badbox";

export type SourceLocation = {
	/**  Absolute, normalized path of the source file. */
	file: string,
	/**  1-based. */
	line: number,
	/**  0-based; 0 when SyncTeX doesn't know the column. */
	column: number,
};

/**  The box to highlight for a forward-search result, in PDF points from the page's top-left. */
export type SynctexRect = {
	/**  1-based page number */
	page: number,
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

export type TableCell = {
	content: string,
	colSpan: number,
	rowSpan: number,
	colSpecOverride: string | null,
	isShadow: boolean,
};

export type TableItem = {
	type?: string,
	file: string,
	filename: string,
	line: number,
	caption: string | null,
	label: string | null,
	byteStart: number,
	byteEnd: number,
};

export type TableModel = {
	columns: ColumnSpec[],
	rows: TableRow[],
	booktabs: boolean,
	caption: string | null,
	label: string | null,
	sourceSpan: Range<number> | null,
	sourceFile: string | null,
};

export type TableOp = { op: "addRow" } | 
/**  Keeps at least one row. */
{ op: "removeRow"; row: number } | { op: "addCol" } | 
/**  Keeps at least one column. */
{ op: "removeCol"; col: number } | { op: "setCell"; row: number; col: number; text: string } | 
/**  Left → center → right → left (a `p{…}` column becomes left). */
{ op: "cycleAlign"; col: number } | { op: "toggleBooktabs" } | 
/**  Merges the rectangle spanned by the two corners. */
{ op: "merge"; row1: number; col1: number; row2: number; col2: number } | { op: "unmerge"; row: number; col: number } | 
/**
 *  Tab-separated rows (as copied from a spreadsheet), starting at the given cell;
 *  the table grows to fit.
 */
{ op: "paste"; row: number; col: number; text: string } | 
/**  Empty or blank clears it. */
{ op: "setCaption"; text: string | null } | { op: "setLabel"; text: string | null };

export type TableRow = {
	cells: TableCell[],
	ruleAbove: RuleKind | null,
	ruleBelow: RuleKind | null,
};

export type ThemePreference = 
/**  Follow the OS appearance. */
"auto" | "light" | "dark";

export type TodoItem = {
	tag: string,
	text: string,
	file: string,
	filename: string,
	line: number,
};

export type TreeNode = {
	name: string,
	path: string,
	type: string,
	children?: TreeNode[] | null,
};

export type WatchedKind = 
/**  `.tex` or `.bib`: indexed. */
"source" | 
/**  A build output; the PDF viewer reloads it. */
"pdf" | 
/**  `.git/HEAD` or `.git/index`: a commit, checkout or stage happened. */
"git";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

